# Generated by Django 5.0.6 on 2024-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
